apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-ui
spec:
  template:
    spec:
      containers:
        - name: dashboard-ui
          image: australia-southeast1-docker.pkg.dev/vital-contact-300805/powerledger-platform/account-service:15.5.4 # {"$imagepolicy": "flux-system:production-dashboard-ui"}
