apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-ui
spec:
  template:
    spec:
      containers:
      - name: dashboard-ui
        image: australia-southeast1-docker.pkg.dev/vital-contact-300805/powerledger-platform/tracex-web-app:5.5.7 # {"$imagepolicy": "flux-system:production-dashboard-ui"}
