---
name: Release Sentry
on:
  workflow_dispatch:
    inputs:
      parameters_json:
        type: string
        required: true

jobs:
  sentry-release:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0
      - run: echo "result=${{steps.something.something-else}}" >> $GITHUB_OUTPUT
        id: result
